image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:

  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose up -d
  - sudo chmod +x aqa-shop.jar &
  - java  -jar aqa-shop.jar &
  - sleep 5
build_script:
  - chmod +x gradlew
  - ./gradlew -Ddb.url=jdbc:mysql://localhost:3306/app test --info "-Dselenide.headless=true"
